using Microsoft.EntityFrameworkCore;

using NDjango.Admin.AspNetCore.AdminDashboard.Authentication.Entities;

namespace NDjango.Admin.AspNetCore.AdminDashboard.Authentication
{
    internal class AuthDbContext : DbContext
    {
        public DbSet<AuthUser> Users { get; set; }
        public DbSet<AuthGroup> Groups { get; set; }
        public DbSet<AuthPermission> Permissions { get; set; }
        public DbSet<AuthGroupPermission> GroupPermissions { get; set; }
        public DbSet<AuthUserGroup> UserGroups { get; set; }

        public AuthDbContext(DbContextOptions<AuthDbContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AuthUser>(entity => {
                entity.HasIndex(e => e.Username).IsUnique();
                // IsSuperuser deliberately has NO HasDefaultValue. A store default makes EF Core mark
                // the property ValueGenerated.OnAdd, and DbContextMetaDataLoader turns anything that
                // is not ValueGenerated.Never into a read-only field — which is why the dashboard
                // rendered the flag greyed out on the change form and hid it on the add form, with
                // no error to explain it. Promoting a user meant an UPDATE by hand against the
                // database. Nothing is lost by dropping it: false is already the CLR default, and
                // the DEFAULT 0 in the column is written by the CREATE TABLE in
                // SqlServerAuthStorageInitializer (the auth tables are never created by EF, so this
                // model does not shape the schema).
                //
                // IsActive KEEPS its default, and that asymmetry is on purpose. Its CLR default is
                // the opposite of the column's, so making it editable changes what a create with the
                // field absent means: the user would come out inactive instead of active. That is
                // what CreatePost_WithValueGeneratedBoolDefault_PreservesDatabaseDefaultAsync pins.
                // Making it editable is worth doing, but it needs the add form to seed the checkbox
                // from the entity default first — a separate change, not a side effect of this one.
                entity.Property(e => e.IsActive).HasDefaultValue(true);
                // GETUTCDATE() is genuinely generated by the database, so read-only is correct here:
                // a creation timestamp is not something to type by hand.
                entity.Property(e => e.DateJoined).HasDefaultValueSql("GETUTCDATE()");
            });

            modelBuilder.Entity<AuthGroup>(entity => {
                entity.HasIndex(e => e.Name).IsUnique();
            });

            modelBuilder.Entity<AuthPermission>(entity => {
                entity.HasIndex(e => e.Codename).IsUnique();
            });

            modelBuilder.Entity<AuthGroupPermission>(entity => {
                entity.HasIndex(e => new { e.GroupId, e.PermissionId }).IsUnique();
                entity.HasOne(e => e.Group).WithMany().HasForeignKey(e => e.GroupId);
                entity.HasOne(e => e.Permission).WithMany().HasForeignKey(e => e.PermissionId);
            });

            modelBuilder.Entity<AuthUserGroup>(entity => {
                entity.HasIndex(e => new { e.UserId, e.GroupId }).IsUnique();
                entity.HasOne(e => e.User).WithMany().HasForeignKey(e => e.UserId);
                entity.HasOne(e => e.Group).WithMany().HasForeignKey(e => e.GroupId);
            });
        }
    }
}
