import { test, expect } from '@fixtures/admin';
import { uniqueName } from '@helpers/random';

test.describe('Phase 4 — AuthUser CRUD', () => {
  test('create form shows editable Username/Password and hides DateJoined/IsSuperuser', async ({
    formFor,
  }) => {
    const form = formFor('AuthUser');
    await form.gotoAdd();

    await expect(form.input('Username')).toBeVisible();
    await expect(form.input('Password')).toBeVisible();
    await expect(form.input('Password')).toHaveAttribute('type', 'password');

    // IsActive is auto-generated by DB default (renders as readonly text).
    await expect(form.readonlyValue('IsActive')).toBeVisible();
    await expect(form.readonlyValue('IsActive')).toContainText('True');

    // DateJoined and IsSuperuser are not rendered on the create form
    // (DB defaults via GETUTCDATE() / 0).
    await expect(form.input('DateJoined')).toHaveCount(0);
    await expect(form.input('IsSuperuser')).toHaveCount(0);
  });

  test('create new user defaults IsActive=True via DB default', async ({
    page,
    listFor,
    formFor,
  }) => {
    const username = uniqueName('user');
    const list = listFor('AuthUser');
    const form = formFor('AuthUser');

    await form.gotoAdd();
    await form.submit({ Username: username, Password: 'plain-password' }, 'save');

    await expect(page).toHaveURL(/\/admin\/AuthUser\/(\?|$)/);
    await list.gotoLatest();
    const row = list.rowByText(username);
    await expect(row).toBeVisible();
    await expect(row).toContainText('True');
  });

  test('edit form shows hashed password (not plaintext)', async ({
    listFor,
    formFor,
  }) => {
    const username = uniqueName('user');
    const password = 'plain-password';

    const form = formFor('AuthUser');
    const list = listFor('AuthUser');

    await form.gotoAdd();
    await form.submit({ Username: username, Password: password }, 'save');

    await list.gotoLatest();
    await list.clickRowLink(username);
    // Password input is type="password" with empty value (autocomplete=new-password).
    // Verify input renders as password type and is empty (we don't expose hash to client).
    const passwordInput = form.input('Password');
    await expect(passwordInput).toHaveAttribute('type', 'password');
    await expect(passwordInput).toHaveValue('');
  });
});
