import { test, expect } from '@fixtures/admin';
import { uniqueName } from '@helpers/random';

test.describe('Phase 4 — AuthUser CRUD', () => {
  test('create form shows editable Username/Password/IsSuperuser and hides DateJoined', async ({
    formFor,
  }) => {
    const form = formFor('AuthUser');
    await form.gotoAdd();

    await expect(form.input('Username')).toBeVisible();
    await expect(form.input('Password')).toBeVisible();
    await expect(form.input('Password')).toHaveAttribute('type', 'password');

    // IsSuperuser is editable — it decides whether someone can do anything in the dashboard, so
    // it has to be settable from the dashboard. It used to carry a store default, which EF Core
    // marks ValueGenerated.OnAdd and the metadata loader turns into a read-only field.
    await expect(form.checkbox('IsSuperuser')).toBeVisible();
    await expect(form.checkbox('IsSuperuser')).not.toBeChecked();

    // IsActive keeps its store default, so it still renders as readonly text. The asymmetry is
    // deliberate: its CLR default is the opposite of the column's, so making it editable would
    // turn a create that leaves the box alone into an inactive user.
    await expect(form.readonlyValue('IsActive')).toBeVisible();
    await expect(form.readonlyValue('IsActive')).toContainText('True');

    // DateJoined is genuinely generated by the database (GETUTCDATE()), so it is not rendered.
    await expect(form.input('DateJoined')).toHaveCount(0);
  });

  test('create a superuser from the form and it persists', async ({
    page,
    formFor,
  }) => {
    const username = uniqueName('superuser');
    const form = formFor('AuthUser');

    await form.gotoAdd();
    await form.submit(
      { Username: username, Password: 'plain-password', IsSuperuser: true },
      'continue'
    );

    // Landing on the change form means the create went through; the checkbox coming back checked
    // means the flag actually reached the database. Before IsSuperuser was made editable this was
    // impossible from the dashboard — promoting a user took an UPDATE by hand.
    await expect(page).toHaveURL(/\/admin\/AuthUser\/\d+\/change\/$/);
    await expect(form.checkbox('IsSuperuser')).toBeChecked();
  });

  test('create new user defaults IsActive=True via DB default', async ({
    page,
    listFor,
    formFor,
  }) => {
    const username = uniqueName('user');
    const list = listFor('AuthUser');
    const form = formFor('AuthUser');

    await form.gotoAdd();
    await form.submit({ Username: username, Password: 'plain-password' }, 'save');

    await expect(page).toHaveURL(/\/admin\/AuthUser\/(\?|$)/);
    await list.gotoLatest();
    const row = list.rowByText(username);
    await expect(row).toBeVisible();
    await expect(row).toContainText('True');
  });

  test('edit form shows hashed password (not plaintext)', async ({
    listFor,
    formFor,
  }) => {
    const username = uniqueName('user');
    const password = 'plain-password';

    const form = formFor('AuthUser');
    const list = listFor('AuthUser');

    await form.gotoAdd();
    await form.submit({ Username: username, Password: password }, 'save');

    await list.gotoLatest();
    await list.clickRowLink(username);
    // Password input is type="password" with empty value (autocomplete=new-password).
    // Verify input renders as password type and is empty (we don't expose hash to client).
    const passwordInput = form.input('Password');
    await expect(passwordInput).toHaveAttribute('type', 'password');
    await expect(passwordInput).toHaveValue('');
  });
});
